### ISSUE TITLE
Text error

### ISSUE THREAD

**Issue by gsklee** [nodejitsu/npm-package-json-pagelet#10]
There is a text error on the [live site](http://browsenpm.org/package.json#main):

`...It's highly advised that requiring the main file does generate any side affects.`

Should be "does **not** generate any side affects"; however I'm not seeing this error inside the codebase which is curious:

https://github.com/nodejitsu/npm-package-json-pagelet/blob/0ade43255ad211643a28d1fe169c3163d5ca394b/view.html#L228

**Comment by 3rd-Eden** [comment]
@gsklee Could be that this module wasn't updated with a re-deploy.
